# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'BmobSDK'
pod 'HyphenateFullSDK', '~> 3.1.5'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh', '~> 3.1.12'
target 'MyPet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyPet

  target 'MyPetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyPetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
