# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'BmobSDK'
pod 'HyphenateFullSDK', '~> 3.1.5'
pod 'MJRefresh', '~> 3.1.12'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
#新浪微博弹窗
pod 'BHBPopView'
#// Mob产品公共库
pod 'MOBFoundation_IDFA'
#// SMSSDK必须
pod 'SMSSDK'
target 'MyPet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyPet

  target 'MyPetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyPetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
